name: Daily Shift Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-shift-aggregator:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Write Google credentials
        run: echo "$GOOGLE_CREDS" > credentials.json
      - name: Run shift scripts
        run: |
          python email_shift_extractor.py
          # Add other scripts as needed
