name: Run All Shift Scripts

on:
  workflow_dispatch:      # Manual trigger
  schedule:
    - cron: '0 6 * * *'   # Every day at 6:00 AM UTC

jobs:
  run-shifts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write token.json
        run: |
          printf '%s' "${{ secrets.TOKEN_JSON }}" > token.json
              
      - name: Write Google credentials
        run: printf '%s' "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

      - name: Run email shift extractor
        run: python email_shift_extractor.py

      - name: Run WhatsApp shift parser
        run: python whatsapp_shift_parser.py

      - name: Add shifts to sheets
        run: python add_shifts_to_sheets.py
